title: CriptoArgentina.net
description: Cripto para una sociedad resiliente 
url: https://criptoargentina.net
language: es
baseurl: ''

social:
  reddit: CriptoArgentina

sass:
  style: compressed

plugins:
  - jekyll-sitemap

compress_html:
  clippings: all
  comments: all
  endings: all
  blanklines: false
  profile: false